import { useState } from 'react'
import { Download, FileText, Loader2 } from 'lucide-react'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  Button,
} from '@/components/ui'
import { useUIStore, useViewerStore, useNotesStore, useQuizStore } from '@/stores'
import { machines } from '@/data/machines'
import { getPartsByMachine } from '@/data/parts'

export function ExportModal() {
  const { exportModalOpen, setExportModalOpen, language } = useUIStore()
  const { currentMachine } = useViewerStore()
  const { notes } = useNotesStore()
  const { results } = useQuizStore()

  const [isExporting, setIsExporting] = useState(false)
  const [includeNotes, setIncludeNotes] = useState(true)
  const [includeQuiz, setIncludeQuiz] = useState(true)

  const machine = currentMachine ? machines[currentMachine] : null
  const machineNotes = notes.filter((n) => n.machineId === currentMachine)
  const machineResults = results.filter((r) => r.machineId === currentMachine)

  const handleExport = async () => {
    if (!currentMachine || !machine) return

    setIsExporting(true)

    try {
      // Dynamic import for code splitting
      const { jsPDF } = await import('jspdf')

      const doc = new jsPDF()
      const pageWidth = doc.internal.pageSize.getWidth()
      let yPos = 20

      // Title
      doc.setFontSize(24)
      doc.setFont('helvetica', 'bold')
      doc.text('SIMVEX', pageWidth / 2, yPos, { align: 'center' })
      yPos += 10

      doc.setFontSize(18)
      doc.text(machine.name, pageWidth / 2, yPos, { align: 'center' })
      yPos += 8

      doc.setFontSize(12)
      doc.setFont('helvetica', 'normal')
      doc.text(machine.nameKo, pageWidth / 2, yPos, { align: 'center' })
      yPos += 15

      // Description
      doc.setFontSize(10)
      const description = language === 'ko' ? machine.descriptionKo : machine.description
      const splitDesc = doc.splitTextToSize(description, pageWidth - 40)
      doc.text(splitDesc, 20, yPos)
      yPos += splitDesc.length * 5 + 10

      // Parts list
      doc.setFontSize(14)
      doc.setFont('helvetica', 'bold')
      doc.text(language === 'ko' ? '부품 목록' : 'Parts List', 20, yPos)
      yPos += 8

      const parts = getPartsByMachine(currentMachine)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')

      parts.forEach((part, index) => {
        if (yPos > 270) {
          doc.addPage()
          yPos = 20
        }
        const partName = language === 'ko' ? part.nameKo : part.name
        const material = language === 'ko' ? part.materialKo : part.material
        doc.text(`${index + 1}. ${partName} - ${material}`, 25, yPos)
        yPos += 6
      })

      yPos += 10

      // Notes section
      if (includeNotes && machineNotes.length > 0) {
        if (yPos > 240) {
          doc.addPage()
          yPos = 20
        }

        doc.setFontSize(14)
        doc.setFont('helvetica', 'bold')
        doc.text(language === 'ko' ? '학습 노트' : 'Study Notes', 20, yPos)
        yPos += 8

        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')

        machineNotes.forEach((note) => {
          if (yPos > 260) {
            doc.addPage()
            yPos = 20
          }
          doc.setFont('helvetica', 'bold')
          doc.text(note.title, 25, yPos)
          yPos += 5
          doc.setFont('helvetica', 'normal')
          if (note.content) {
            const splitContent = doc.splitTextToSize(note.content, pageWidth - 50)
            doc.text(splitContent, 25, yPos)
            yPos += splitContent.length * 5 + 5
          }
        })

        yPos += 5
      }

      // Quiz results section
      if (includeQuiz && machineResults.length > 0) {
        if (yPos > 240) {
          doc.addPage()
          yPos = 20
        }

        doc.setFontSize(14)
        doc.setFont('helvetica', 'bold')
        doc.text(language === 'ko' ? '퀴즈 결과' : 'Quiz Results', 20, yPos)
        yPos += 8

        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')

        const latestResult = machineResults[0]
        if (latestResult) {
          const percentage = Math.round((latestResult.score / latestResult.totalQuestions) * 100)
          doc.text(
            `${language === 'ko' ? '최근 점수' : 'Latest Score'}: ${latestResult.score}/${latestResult.totalQuestions} (${percentage}%)`,
            25,
            yPos
          )
          yPos += 6
        }
      }

      // Footer
      doc.setFontSize(8)
      doc.setTextColor(128)
      doc.text(
        `Generated by SIMVEX - ${new Date().toLocaleDateString()}`,
        pageWidth / 2,
        285,
        { align: 'center' }
      )

      // Save the PDF
      doc.save(`SIMVEX_${machine.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`)
    } catch (error) {
      console.error('Failed to export PDF:', error)
    } finally {
      setIsExporting(false)
    }
  }

  return (
    <Dialog open={exportModalOpen} onOpenChange={setExportModalOpen}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            {language === 'ko' ? 'PDF 내보내기' : 'Export PDF'}
          </DialogTitle>
          <DialogDescription>
            {language === 'ko'
              ? '학습 자료를 PDF 문서로 내보냅니다.'
              : 'Export your study materials as a PDF document.'}
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {/* Machine info */}
          <div className="p-3 rounded-lg bg-muted">
            <p className="font-medium">{machine?.name}</p>
            <p className="text-sm text-muted-foreground">{machine?.nameKo}</p>
          </div>

          {/* Options */}
          <div className="space-y-3">
            <label className="flex items-center gap-3 cursor-pointer">
              <input
                type="checkbox"
                checked={includeNotes}
                onChange={(e) => setIncludeNotes(e.target.checked)}
                className="w-4 h-4 rounded border-gray-300"
              />
              <span className="text-sm">
                {language === 'ko' ? '노트 포함' : 'Include Notes'}
                <span className="text-muted-foreground ml-1">
                  ({machineNotes.length})
                </span>
              </span>
            </label>
            <label className="flex items-center gap-3 cursor-pointer">
              <input
                type="checkbox"
                checked={includeQuiz}
                onChange={(e) => setIncludeQuiz(e.target.checked)}
                className="w-4 h-4 rounded border-gray-300"
              />
              <span className="text-sm">
                {language === 'ko' ? '퀴즈 결과 포함' : 'Include Quiz Results'}
                <span className="text-muted-foreground ml-1">
                  ({machineResults.length})
                </span>
              </span>
            </label>
          </div>
        </div>

        <div className="flex justify-end gap-2">
          <Button variant="outline" onClick={() => setExportModalOpen(false)}>
            {language === 'ko' ? '취소' : 'Cancel'}
          </Button>
          <Button onClick={handleExport} disabled={isExporting}>
            {isExporting ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                {language === 'ko' ? '내보내는 중...' : 'Exporting...'}
              </>
            ) : (
              <>
                <Download className="h-4 w-4 mr-2" />
                {language === 'ko' ? '다운로드' : 'Download'}
              </>
            )}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}
